### ISSUE TITLE
Swift 4.2 support

### ISSUE THREAD

**Issue by gfontenot** [square/SuperDelegate#30]
Swift 4.2 introduced a _bunch_ of churn around imported UIKit interfaces. The result is that SuperDelegate fails to build with Swift 4.2 entirely.

I'm happy to do the work to update the library for 4.2, but before I do: how have these updates been handled in the past. Do we want to maintain backwards compatibility, or do we want to bump the version number and only support 4.2+?

**Comment by dfed** [comment]
Since development on this project is not terribly active, I'd be fine with a major version bump and a breaking change. However, if we go the breaking change route it may be best to drop support for iOS 8 and Xcode's 7-9 given #14. Note you'll want to do a pass on the README to better reflect the current versioning.

Maintaining backwards compatibility would allow us to not bump a major version, but given how long we've been at 0.9, and given that we don't have plans to add new features to 0.9 (right?) I don't see a whole lot of benefit.

**Comment by irccc** [comment]
So is there any chance that anyone will be upgrading this useful library to latest versions of swift..???
